### ISSUE TITLE
urls should be lowercase and use hyphens instead of underscore

### ISSUE THREAD

**Issue by 1000camels** [DenverArtMuseum/biophilia-pub#16]
In general, it is good practice to use all lowercase for urls. This helps to avoid issues where systems are case-sensitive, which is not the case where we are presently hosting, but could be an issue down the road.

As well, it is best to use hyphens instead of the underscores, as they are more legible if any text showing a url is underlined.

If you are ok with this, I will rename the pages. We should do this before setting up all the links.

I am just being very cautious. If Matt thinks I am being overly-cautious, I will defer.

**Comment by vhellstein** [comment]
Thanks, Darcy, for explaining this. That makes total sense to me. I'm okay with you renaming the pages. I'll keep this in mind going forward.
