### ISSUE TITLE
Images added to repo

### ISSUE THREAD

**Issue by vhellstein** [DenverArtMuseum/biophilia-pub#2]

**Comment by 1000camels** [comment]
I am seeing some image ids with the characters \~1 and \~2. The backslash may be an escape character for the tilda, but either way, it does not work as a figure id in markdown. 

So when adding these images, we should stick to simple characters like . or -

**Comment by 1000camels** [comment]
Is there an Excel for the Image log? We might be able to convert this to YAML and save us some time.

**Comment by 1000camels** [comment]
@mpopke list of missing figures:

[quire] WARN	 shortcodes:figure              The figure id "exrr-2023-86" was found in the template "./content/natural-analogs/index.md", but is not defined in "figures.yaml"
[quire] WARN	 shortcodes:figure              The figure id "exrr-2023-87" was found in the template "./content/natural-analogs/index.md", but is not defined in "figures.yaml"
[quire] WARN	 shortcodes:figure              The figure id "2022-57" was found in the template "./content/natural-analogs/index.md", but is not defined in "figures.yaml"
[quire] WARN	 shortcodes:figure              The figure id "exrr-2023-133" was found in the template "./content/natural-systems/index.md", but is not defined in "figures.yaml"
[quire] WARN	 shortcodes:figure              The figure id "ptl-24707" was found in the template "./content/topophilia/index.md", but is not defined in "figures.yaml"
[quire] WARN	 shortcodes:figure              The figure id "exrr-2023-44" was found in the template "./content/topophilia/index.md", but is not defined in "figures.yaml"
[quire] WARN	 shortcodes:figure              The figure id "TL-45469-1" was found in the template "./content/natural-analogs/object-plates/elena-manferdini.md", but is not defined in "figures.yaml"
[quire] WARN	 shortcodes:figure              The figure id "TL-45469-2" was found in the template "./content/natural-analogs/object-plates/elena-manferdini.md", but is not defined in "figures.yaml"
[quire] WARN	 shortcodes:figure              The figure id "TL-45469-3" was found in the template "./content/natural-analogs/object-plates/elena-manferdini.md", but is not defined in "figures.yaml"
[quire] WARN	 shortcodes:figure              The figure id "exrr-2023-89" was found in the template "./content/natural-analogs/object-plates/joris-laarman.md", but is not defined in "figures.yaml"
[quire] WARN	 shortcodes:figure              The figure id "EXRR.2023.137" was found in the template "./content/topophilia/object-plates/alexandra-kehayoglou.md", but is not defined in "figures.yaml"

**Comment by mpopke** [comment]
All of these aside from ptl-24707 should be resolved. We still don't have an image for that one.
