### ISSUE TITLE
First Changes: Navigation

### ISSUE THREAD

**Issue by vhellstein** [DenverArtMuseum/biophilia-pub#21]

**Comment by vhellstein** [comment]
--Can the navigation bar be slightly taller? See [Newfields page](https://paintings.theclowescollection.org/foreword/) 

--no Biophilia logo in top navigation bar; exhibition title instead [it’s too hard to read/color doesn’t match] 

--no DAM logo in top navigation bar 

--navigation should always be visible on top bar (shouldn’t have to scroll over it);  

-- We also like NEWFIELDS graphic treatment of CONTENTS and SEARCH icons at top right of NEWFIELDS: The oval / bubble around CONTENT MENU aligns with our footnotes – we like this consistency (see Newfields link above) 


--Next and Back buttons at bottom of page need to be visible at all times 

--keyboard arrows should not advance through pages: @1000camels is this possible? If too hard, we can re-assess

--When you click search, can the field open just below NAVIGATION bar and not a new page
, like [](https://paintings.theclowescollection.org/building-the-clowes-collection/)

-- NAVIGATION arrows and content are not centered / misaligned with page HEADINGS: Align/center content, remove color when hovering over – Can we do something like the Perfectly Imperfect nav arrows? Darrin suggested a pointing hand/finger. But I'm not so sure about that.

**Comment by 1000camels** [comment]
Where is the exhibition title logo?

Why remove the keyboard arrows? Do you feel like this causes problems with the experience? It is easy to remove. It is a feature I added.

**Comment by 1000camels** [comment]
Just noticed that Newfields uses keyboard navigation, but theirs is CTRL/CMD + arrows. Shall we do the same?

**Comment by vhellstein** [comment]
I'll let @mpopke comment on the keyboard navigation.

Also, @mpopke, do we want to use the exhibition logo anywhere? It's possible that the actual logo (which I don't think we had before when we sent everything to Darcy) might be more legible?

**Comment by 1000camels** [comment]
I've adjusted the keyboard navigation to use ctrl/cmd+arrows. I can always disable that if you wish.

I have just made the title an h1 in the navbar. We can remove it later if they object
