### ISSUE TITLE
First Changes: Section Landing Pages

### ISSUE THREAD

**Issue by vhellstein** [DenverArtMuseum/biophilia-pub#26]

**Comment by vhellstein** [comment]
- [ ] delete Section Landing pages

**Comment by 1000camels** [comment]
I have removed them from the previous/next flow but they still exist as pages, which you can get to from the TOC and menu.
The pages need to exist, so I am looking for a way to redirect from them to the first page.
We could also leave them as a TOC page or just a splash page, which would only be visited if someone links to it from the TOC and menu.

**Comment by vhellstein** [comment]
Is it possible to hide them from the TOC and menu?

**Comment by 1000camels** [comment]
I have moved forward with making the section title essay the index page, so this avoids this issue. But Greg Albers gave me some code that will help with this situation, which I can use for the Object Plates subsections, which I will create today
