### ISSUE TITLE
Second Changes: Contents Page

### ISSUE THREAD

**Issue by vhellstein** [DenverArtMuseum/biophilia-pub#46]

**Comment by vhellstein** [comment]
- [ ] @1000camels Make "Contents" heading a little smaller, but the spacing between the heading and the content is good
- [ ] @vhellstein move Acknowledgments after Director's Forword
- [ ] @vhellstein  change Recommending Readings to Recommended Reading
- [ ] @1000camels The contrast between the essay title text color and the link/hover color needs to have more contrast
- [ ] @1000camels Essay titles should be bolded (and hopefully NOT capped...waiting for Darrin's approval)
- [ ] @1000camels Add authors names only on contents page (not hamburger), in italics
- [ ] @1000camels Fix bolding, size,  and spacing  between Section Essays, Object Plates, and those individual entries. See image.

![Image](https://github.com/DenverArtMuseum/biophilia-pub/assets/119438504/ad79f99a-0e8f-4150-b30c-3b90872a884b)

**Comment by 1000camels** [comment]
The link colour is the dark blue. What other color can I use?

**Comment by vhellstein** [comment]
@mpopke is exploring a green that might work that coordinates with the wall colors of the exhibition. Maybe that could work?

**Comment by vhellstein** [comment]
@1000camels can "Object Plates" be the same size as the titles of Darrin's essay?

**Comment by vhellstein** [comment]
@1000camels all of the checklist objects are showing up on the Contents page again. Can you hide them?
