### ISSUE TITLE
Second Changes: Introduction

### ISSUE THREAD

**Issue by vhellstein** [DenverArtMuseum/biophilia-pub#48]

**Comment by vhellstein** [comment]
- [ ] Waiting for Darrin's thoughts, but @1000camels we may need to force the size of the hero image to match the ratio of this particular image, which can't be cropped (per the artist). I know that with responsive design, there will still be cropping. We may change the image. Stay tuned.
- [ ] @1000camels no matter, the image, we'd like title/Darrin's name and title below the hero image not on top of it. See image.
- [ ] @vhellstein will add caption for hero image at the bottom of the md file

![Image](https://github.com/DenverArtMuseum/biophilia-pub/assets/119438504/2cf62911-301e-402c-af32-45f781784a19)

**Comment by 1000camels** [comment]
The hero image is created by adding it as a background image. Background images work great for content sitting over top. I can nevertheless push the title down out of the box, but I think to maintain the exact aspect of this image, we need to add it as an image (not a hero image) and we will need to black box (or some other color) it for when the window dimensions do not match.

**Comment by 1000camels** [comment]
I was also planning on adding the captions the way I did in Her Brush, as an (i) icon over the corner of the image which can be expanded. Do you want?
I had partially added this technique, but since v1 has different templates, I wasn't able to copy my code over.

**Comment by vhellstein** [comment]
@1000camels Let's try it, and give Darrin the option. We can delete either that icon or the caption at the bottom of the essay depending on which he prefers.

**Comment by 1000camels** [comment]
Sorry, I need some more time to implement the collapsed caption over the hero image in v1. The template has changed more than I thought.

**Comment by vhellstein** [comment]
@1000camels the (i) button doesn't show up on the intro hero image--do I need need to add a different line from the others to that page?

**Comment by vhellstein** [comment]
@1000camels do I just need to put an image_creit in the page yaml for the intro image (i)?

**Comment by 1000camels** [comment]
yes
