### ISSUE TITLE
caption in Manferdini entry

### ISSUE THREAD

**Issue by vhellstein** [DenverArtMuseum/biophilia-pub#59]

**Comment by vhellstein** [comment]
@1000camels the caption in the Manferdini Object Plate in Natural Analogs is miles away from the video. Can you find a fix for that?

**Comment by 1000camels** [comment]
I am not sure I can change this. Vimeo seems to be serving the video up this way. I also do not have permissions to edit edit or even see the vimeo video, so I cannot understand what is happening.

**Comment by 1000camels** [comment]
There is an option to add aspect_ratio to the video in figures.yaml, but I cannot seem to find the right setting. It still might require fixing it on vimeo

**Comment by mpopke** [comment]
We can add our own aspect ratios. It just requires creating a CSS rule for that aspect ratio. I took care of this for this video.
