### ISSUE TITLE
multi in objects.yaml

### ISSUE THREAD

**Issue by 1000camels** [DenverArtMuseum/biophilia-pub#72]
There is now a field called multi in objects.yaml. Is that a mistake? I am having an issue and I think it might be because of that.

**Comment by 1000camels** [comment]
ok, it looks valid, and as far as I can tell, it should work.
However I am still getting this error on preview:

Original error stack trace: TypeError: Cannot read properties of undefined (reading 'object_list')

**Comment by mpopke** [comment]
Okay. Found it. The YAML interpreter didn't like fields that were italicized unquoted.
