### ISSUE TITLE
Object Plates in the Menu are black and therefore hidden

### ISSUE THREAD

**Issue by 1000camels** [DenverArtMuseum/biophilia-pub#88]
The color of the Object Plates in the Menu are off black and therefore are invisible. Is this intentional? I had fixed the linking.

I think they should be white, with no underline. Shall I fix it?

**Comment by mpopke** [comment]
That is unintentional. If you could, please fix that.

Matt Popke
Developer
720.913.0126
***@***.***
Denver Art Museum
100 W. 14th Avenue Parkway
Denver, CO 80204
Visit www.denverartmuseum.org and sign up for our email updates. The Denver Art Museum salutes the citizens of metro Denver for helping fund arts, culture and science through their support the Scientific and Cultural Facilities District (SCFD).
________________________________

**Comment by 1000camels** [comment]
fixed
